services:
  redis:
    image: redis
    container_name: cache
    restart: always
    networks:
      - bot-network

  bot:
    container_name: bot
    build: .
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - bot_data:/app/data

    restart: always
    networks:
      - bot-network
    ports:
      - "80:80"

#  sqlite_web:
#    image: coleifer/sqlite-web
#    container_name: sqlite_web
#    ports:
#      - "127.0.0.1:777:8080"
#    volumes:
#      - bot_data:/data
#    depends_on:
#      - bot
#    command: ["sqlite_web", "--host", "0.0.0.0", "/data/bot.db"]

volumes:
  bot_data:

networks:
  bot-network:
    driver: bridge
  internet:
    driver: bridge
